"""Git-bound exact execution identity policy for the Evidence E test suite."""

EXPECTED_E_SUITE_TEST_SOURCE_TREE_SHA256 = (
    "52f01b6cf611d62554a3364eefe27d7bf13f98984affb516064e988c74dd5134"
)
EXPECTED_E_SUITE_TESTCASE_IDENTITY_SHA256 = (
    "76df1856fa27c938120bbf9299d2defe5da98b348ccfcc3aa7b7713a9bfda36a"
)
EXPECTED_E_SUITE_TESTCASE_IDENTITIES = (
    "vietnamese_attestation.v1.tests.integration.test_official_input_and_replay::test_cli_json_loader_rejects_duplicate_keys",
    "vietnamese_attestation.v1.tests.integration.test_official_input_and_replay::test_direct_replay_requires_external_manifest_anchor_and_strict_rows",
    "vietnamese_attestation.v1.tests.integration.test_official_input_and_replay::test_official_cli_rejects_loose_complete_input_and_accepts_release_set",
    "vietnamese_attestation.v1.tests.integration.test_official_input_and_replay::test_official_dataset_set_binds_receipt_members_and_candidate_identity",
    "vietnamese_attestation.v1.tests.integration.test_official_input_and_replay::test_official_loader_rejects_receipt_tamper_and_producer_drift",
    "vietnamese_attestation.v1.tests.test_cli_and_boundaries::test_concern_directories_remain_split",
    "vietnamese_attestation.v1.tests.test_cli_and_boundaries::test_offline_cli_writes_a_valid_non_authoritative_package",
    "vietnamese_attestation.v1.tests.test_cli_and_boundaries::test_vietnamese_attestation_does_not_import_context_substitution",
    "vietnamese_attestation.v1.tests.test_contracts::test_frozen_candidate_is_hash_bound",
    "vietnamese_attestation.v1.tests.test_contracts::test_frozen_candidate_rejects_surface_drift",
    "vietnamese_attestation.v1.tests.test_contracts::test_frozen_candidate_rejects_unknown_fields",
    "vietnamese_attestation.v1.tests.test_contracts::test_public_facade_exposes_versioned_input_and_output_contracts",
    "vietnamese_attestation.v1.tests.test_controlled_registry::test_empty_dataset_registry_is_bound_and_blocked_honestly",
    "vietnamese_attestation.v1.tests.test_controlled_registry::test_nonempty_minimum_registry_stays_blocked_until_schema_freeze",
    'vietnamese_attestation.v1.tests.test_controlled_registry::test_registry_preserves_nonfinite_and_trailing_garbage_rejection[{"source_id":"source-1"} trailing\\n]',
    'vietnamese_attestation.v1.tests.test_controlled_registry::test_registry_preserves_nonfinite_and_trailing_garbage_rejection[{"source_id":NaN}\\n]',
    "vietnamese_attestation.v1.tests.test_controlled_registry::test_registry_rejects_duplicate_keys_at_any_object_depth",
    "vietnamese_attestation.v1.tests.test_controlled_registry::test_registry_rejects_hash_drift_and_malformed_identity",
    "vietnamese_attestation.v1.tests.test_engine::test_exhausted_judge_routes_is_unjudgeable_not_negative",
    "vietnamese_attestation.v1.tests.test_engine::test_package_hash_rejects_tampering",
    "vietnamese_attestation.v1.tests.test_engine::test_related_concept_is_supporting_but_not_accepted",
    "vietnamese_attestation.v1.tests.test_engine::test_search_failure_is_reported_without_fabricating_evidence",
    "vietnamese_attestation.v1.tests.test_engine::test_strong_attestation_collapses_duplicate_echo",
    "vietnamese_attestation.v1.tests.test_engine::test_unexpected_extraction_failure_is_not_silenced",
    "vietnamese_attestation.v1.tests.test_engine::test_wrong_sense_is_not_retried_or_accepted",
    "vietnamese_attestation.v1.tests.test_judge_routes::test_hallucinated_evidence_span_falls_back_as_schema_failure",
    "vietnamese_attestation.v1.tests.test_judge_routes::test_router_falls_back_only_for_transport_or_schema_failures",
    "vietnamese_attestation.v1.tests.test_judge_routes::test_three_live_route_shapes_are_supported_without_network",
    "vietnamese_attestation.v1.tests.test_judge_routes::test_valid_negative_semantic_result_does_not_fallback",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_artifact_symlink_is_rejected_when_supported",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_junit_gate_rejects_missing_empty_red_wrong_and_unrelated_reports",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_manifest_refs_reject_unsafe_and_case_confusable_paths",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_post_zero_api_release_is_commit_bound_cache_free_and_honest",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_provider_ledger_duplicate_key_is_rejected",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_r2_authority_and_zero_api_artifact_verify_without_provider_calls",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_r2_authority_and_zero_api_tamper_fail_closed",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_r2_authority_rejects_nonrelease_and_arbitrary_release_drift",
    "vietnamese_attestation.v1.tests.test_post_zero_api_readiness::test_strict_persisted_decoder_rejects_ambiguous_json",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_adapter_package_hash_rejects_identity_tampering",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_modified_source_zip_rejects_before_normalization",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_pilot_rejects_missing_parent_v3",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_public_facade_exposes_real_dataset_adapter",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_real_pilot_binds_v3_parent_and_keeps_authority_unavailable",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_real_v3_maps_exact_candidate_and_sense_identities",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_zero_api_cli_writes_pilot_package_and_receipt",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_zip_member_paths_fail_closed[names0-unsafe_zip_name]",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_zip_member_paths_fail_closed[names1-unsafe_zip_name]",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_zip_member_paths_fail_closed[names2-unsafe_zip_name]",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_zip_member_paths_fail_closed[names3-unsafe_zip_name]",
    "vietnamese_attestation.v1.tests.test_real_dataset_adapter::test_zip_member_paths_fail_closed[names4-case_confusable_zip_name]",
    "vietnamese_attestation.v1.tests.test_retrieval_evidence::test_candidate_span_builds_exact_mask",
    "vietnamese_attestation.v1.tests.test_retrieval_evidence::test_duplicate_echo_collapses_but_same_organization_does_not",
    "vietnamese_attestation.v1.tests.test_retrieval_evidence::test_host_rate_limiter_waits_only_for_same_host",
    "vietnamese_attestation.v1.tests.test_retrieval_evidence::test_http_fetch_retries_timeout_and_caches_success",
    "vietnamese_attestation.v1.tests.test_retrieval_evidence::test_search_retries_transient_timeout",
    "vietnamese_attestation.v1.tests.test_retrieval_evidence::test_url_canonicalization_removes_tracking_only",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_cli_accepts_shared_input_and_preserves_internal_replay",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_internal_package_projects_to_shared_attestation_contract",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_projection_rejects_foreign_internal_candidate",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_same_and_different_evidence_asserts_contradiction",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_semantic_negative_asserts_concept_mismatch_without_fallback",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_shared_candidate_version_uses_shared_string_limit",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_shared_contract_tamper_fails_before_engine",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_shared_frozen_candidate_adapts_without_changing_join_key",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_shared_gate_signal_tamper_rejects_after_valid_reseal",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_v11_input_binding_tamper_fails_even_with_valid_self_hash",
    "vietnamese_attestation.v1.tests.test_shared_contract_bridge::test_weak_and_unjudgeable_packages_assert_evidence_gates",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_attested_without_accepted_evidence_is_rejected",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_cache_preserves_original_retrieved_at",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_each_execution_has_unique_id_but_stable_spec",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_file_audit_store_keeps_terminal_urls_and_invalid_judge_raw",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_general_word_cannot_be_attested",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_machine_translation_exclusion_policy_is_explicit",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_main_content_excludes_navigation_only_candidate",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_min_words_is_enforced",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_non_vietnamese_page_is_not_sent_to_judge",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_span_yield_prevents_full_coverage",
    "vietnamese_attestation.v1.tests.test_v11_rework::test_unknown_pdf_is_not_promoted_to_tier_b",
    "vietnamese_attestation.v1.tests.test_zero_api_pilot::test_real_pilot_runs_all_15_candidates_without_external_api",
    "vietnamese_attestation.v1.tests.test_zero_api_pilot::test_zero_api_pilot_is_deterministic_and_replay_detects_tamper",
)

EXPECTED_E_SUITE_TEST_COUNT = len(EXPECTED_E_SUITE_TESTCASE_IDENTITIES)

__all__ = [
    "EXPECTED_E_SUITE_TEST_COUNT",
    "EXPECTED_E_SUITE_TEST_SOURCE_TREE_SHA256",
    "EXPECTED_E_SUITE_TESTCASE_IDENTITIES",
    "EXPECTED_E_SUITE_TESTCASE_IDENTITY_SHA256",
]
